docker-compose fixes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,13 +28,21 @@ jobs:
         run: echo "BASE_URL=$BASE_URL"
 
       - name: Run services with Docker Compose
-        run: docker-compose up --build -d
+        run: docker compose up --build -d
 
       - name: Wait for services to be ready
-        run: sleep 10
+        run: sleep 10  # Servislerin ayağa kalkması için bekle
 
-      - name: Run tests
-        run: docker-compose run --rm api-tests
+      - name: Check mock-service hostname resolution
+        run: docker compose run --rm api-tests sh -c 'ping -c 3 mock-service || echo "ping failed"'
+
+      - name: Check hosts file inside api-tests container
+        run: docker compose run --rm api-tests cat /etc/hosts
+
+      - name: Run Pytest inside Docker Compose service
+        run: docker compose run --rm api-tests pytest tests/
+
+
 
       - name: Stop and remove containers
         run: docker-compose down
